---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: no-reply@global-communications-academy.com
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: eu-west-2
            hostedZoneID: Z03727731PTWROEM6WW82

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-openedx-dev-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: dev.global-communications-academy.com
  dnsNames:
    - "*.dev.global-communications-academy.com"
