LMS_HOSTNAME=dev.global-communications-academy.com
CMS_HOSTNAME=studio.dev.global-communications-academy.com
DOCKER_IMAGE_OPENEDX=824885811700.dkr.ecr.eu-west-2.amazonaws.com/openedx:12.1.3-202110110854
